### ISSUE TITLE
Cameras Not Showing In Homekit

### ISSUE THREAD

**Issue by DynamicTTD** [kopiro/homebridge-tapo-camera#101]
**Describe The Bug:**
Since updating to version V2.3.3 My C310 & my C510W are not working not getting any errors they just dont show up all im getting on log is  manually add in home app but doesnt show up these cameras have worked for months and now even if i fully reinstall with the version i was previously using i get the same thing

**Logs:**

```[12/4/2023, 5:19:24 PM] Please add [Driveway DDE6] manually in Home app. Setup Code: 875-66-455
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 3.2.2
* **Homebridge Version**:  v1.1.7-beta.6
* **Node.js Version**: 
v20.10.0

* **Operating System**: 
Docker

**Comment by kopiro** [comment]
Try latest version please: https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.3.4
