### ISSUE TITLE
Several cameras in single Platform

### ISSUE THREAD

**Issue by enevold** [kopiro/homebridge-tapo-camera#11]
Hi kopiro

How do you add several cameras to the same configuration?

**Comment by kopiro** [comment]
```json
{
  "platform": "TAPO-CAMERA",
  "cameras": [
    {
      "name": "Camera 2",
      "ipAddress": "__IP_ADDRESS__",
      "password": "__PASSWORD__",
      "streamPassword": "__STREAM_PASSWORD__",
      "streamUser": "__STREAM_USER__",
    },
{
      "name": "Camera 1",
      "ipAddress": "__IP_ADDRESS__",
      "password": "__PASSWORD__",
      "streamPassword": "__STREAM_PASSWORD__",
      "streamUser": "__STREAM_USER__",
    }
  ]
}
```

**Comment by enevold** [comment]
Ahh perfect, I will try that, I was missing the comma from first to next. Thank you for the update.

**Comment by enevold** [comment]
Seems like I have trouble to connect to the Tapo C100 Stream, but snaps works, the C200 works in the system.

**Comment by enevold** [comment]
Hi Kopiro

The above works fine, although i can not get the live video to work, but the single snapsots work within the HomeKit.

I know the Tapo cams is accessible with port 2020, so not sure what prevents that within the HomeBridge setup.

Seems a little odd when Snapshots works that the live video do not, any idea?

/Enevold

**Comment by kopiro** [comment]
Hey, I've seen this issue with another phone on the same network. I'm not actually sure how to solve it, can you post the debug logs?

**Comment by enevold** [comment]
Yea i can do that but do you mean just the normal log seen on the HomeBridge console?

**Comment by ricbacca** [comment]
HI. I'm also getting this same problem, with almost the same debug logs

**Comment by ricbacca** [comment]
I've noted on your "camera accessory" file, from line 146, you use different parameters configuration as compared to homebridge-camera-ffmpeg plugin(here: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1213)
Maybe, it's possible to reduce the problem using low resolutions and in general low values for parameters.
Because for me, seems that the problem is that with too much cameras connected, there are bandwidths problem for changing data between plugin and the cameras, slowing down homebridge instances.

**Comment by kopiro** [comment]
Yes, that configuration is using the `stream2` instead of `stream1` that is a low-resolution stream.
I can try to check if this is the issue and anyway add a parameter you can specify to be able to set HIGH | LOW.

**Comment by ricbacca** [comment]
Exactly, great choice !

**Comment by kopiro** [comment]
Do you think you can try this branch? https://github.com/kopiro/homebridge-tapo-camera/pull/13

**Comment by ricbacca** [comment]
Hi. I'm not sure on how to do it, I'm a beginner on homebridge and I'm already studying it to know how it works, and test somethings.

**Comment by kopiro** [comment]
You can try latest update (v1.5.0) and set `lowQuality: true` in the config

**Comment by enevold** [comment]
I testes Also on my Mac monterey HomeKit app and here The video shows up fine but not on iPhone 7

**Comment by ricbacca** [comment]
Same for me as @enevold, on Mac os it runs ok, but on iPhone live view does not run, but preview images of videos, runs ok.

**Comment by enevold** [comment]
Hi kopiro / ricbacca

I added "lowQuality": true, to all 3 cams I have 2 x C100 and 1 x C200, and that helped for the iPhone 7.
Only one of the C100 seems to not still want to deal with this, I will try a restart and when else I can figure.
also it now comes up with the video although it takes some seconds before the video streams.

Thanks for the fix/update. pretty good.

/Enevold
