### ISSUE TITLE
C110 Not Working - "data" undefined

### ISSUE THREAD

**Issue by Valvify** [kopiro/homebridge-tapo-camera#112]
**Describe Your Problem:**
I get an undefined "data" argument whenever I try configuring my camera, I have confirmed the RTSP stream works through VLC (rtsp://\<username\>:\<password\>@192.168.0.37:554/stream1).

**Logs:**

```
[31/12/2023, 23:25:37] [tapo-camera] Initializing tapo-camera platform...
[31/12/2023, 23:25:37] [tapo-camera] Error during setup of camera Living Room Camera The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "<redacted>",
        "port": 51424,
        "pin": "<redacted>",
        "advertiser": "ciao"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "cameras": [
                {
                    "name": "Living Room Camera",
                    "ipAddress": "192.168.0.37",
                    "streamUser": "<redacted>",
                    "streamPassword": "<redacted>",
                    "debug": true
                }
            ],
            "platform": "tapo-camera"
        }
    ],
    "disabledPlugins": []
}
```

**Environment:**

* **Plugin Version**: 2.3.4
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 20.10.0
* **NPM Version**: 10.2.5
* **Operating System**: hb-service

**Comment by marcos-arsoares** [comment]
I get the same problem. Still no fix

**Comment by EddieDSuza** [comment]
You will need to add a Camera name to address this issue. It's the first field to populate.

**Comment by Valvify** [comment]
> You will need to add a Camera name to address this issue. It's the first field to populate. 

I've set it to "Living Room Camera", mirroring the Tapo app, but I get the same issue.

**Comment by brakulla** [comment]
I had this issue due to empty cloud password field. Filling it fixed the issue for me.

**Comment by Valvify** [comment]
> I had this issue due to empty cloud password field. Filling it fixed the issue for me.

That seems to have worked for me. I'm unable to turn on/off the alarm or motion sensing, but this'll do. Thanks for your help!

**Comment by jakubkasparek** [comment]
has anyone managed to get C110 (v2) up and running.
Originally it worked for me as long as I completely disabled internet access, but only until I turned the camera off and on.


I have now downgraded the firmware to:
Tapo_C110v2_en_1.1.16_Build_220805_Rel.1965n_u_1664445156595.bin
but it still won't work in homebridge.
