### ISSUE TITLE
FFmpeg exited with code: null and signal: SIGSEGV (Unexpected)

### ISSUE THREAD

**Issue by fcoppey** [kopiro/homebridge-tapo-camera#122]
This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Camera C210' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

I get this Error on C210 camera with firmware version 1.3.11, is it a known issue? 
I have just ordered a new camera the C225, will I encounter the same issue?

**Comment by wolpax** [comment]
Hello,
do you have a Raspi 5?
On my Pi5 I have the same error, on my Pi4 it works.
The same with the CameraUI plugin.
I'm currently looking for a solution. Did you find out anything?

**Comment by escapeboy** [comment]
For me in JSON config, in camera config disabling the audio fixes the issue.
`"videoConfig": {
                "audio": false
            }`
Also ffmpeg seems to work fine but there is some kind of issue with srtp protocol. I copied the command for the video removing the srtp part and it was fine.
