### ISSUE TITLE
Imou camera

### ISSUE THREAD

**Issue by KimMeersman** [kopiro/homebridge-tapo-camera#125]
Hi,

It may sound stupid but it looks like the Tapo interface looks similar to the Imou interface, seen from the apple store app.
Even the cameras seem like almost an exact copy.
So I was wondering with a few changes in the coding the we can pull a new plugin for Imou cameras, since it does not exist.
I would try to modify the code for myself but I am afraid my coding skills would not be good enough.

Good idea?
greetings,
Kim

**Comment by kopiro** [comment]
Have you tried if the plugin works already out of the box?

**Comment by KimMeersman** [comment]
> Have you tried if the plugin works already out of the box?
Hi,

Thanks for your reply,
I've tried this yes, but in the tape app you only can add TP link camera's.
Fixed it to use the scrypted implementation.

thanks anyway!
