### ISSUE TITLE
Accessories appear to be not working

### ISSUE THREAD

**Issue by KatkayApps** [kopiro/homebridge-tapo-camera#128]
Accessories appear not to be working
I tap on the accessories in the homebridge window and they do nothing, or I do not understand what they are supposed to do. 

I see this status message on homebridge. 

126/04/2024,
23:24:42] [tapo-camera] E
rror at 'getStatusAndUpdateCharacteris tics'. Error: Invalid authentication d ata at TAPOCamera.refreshStok (/var/li b/homebridge/node_modules/homebridge-t apo-camera/src/tapoCamera.ts:289:11)
at processTicksAndRejections (node
: internal/process/task_queues: 95:5)
at TAPOCamera.getAuthenticatedAPIU
RI (/var/lib/homebridge/node_modules/h omebridge-tapo-camera/src/tapoCamera.t s:335:19)
at /var/lib/homebridge/node_module s/homebridge-tapo-camera/src/tapoCamer a.ts:415:23
at TAPOCamera.getStatus (/var/lib/ homebridge/node_modules/homebridge-tap o-camera/src/tapoCamera.ts:555:18)
at CameraAccessory.getStatusAndUpd ateCharacteristics (/var/lib/homebridg e/node_modules/homebridge-tapo-camera/ src/cameraAccessory.ts:234:27)
at Timeout._onTimeout (/var/lib/ho mebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)

I am using a Raspberry Pi Zero 2W with a 64 gb card

I can see the camera on Home.app. 

When I open the HB accessory panel I see 3 things: the trigger, the privacy and the alarm accessories. The trigger updates with "triggered" If movement is detected, but the other two I can turn on or off but despite their status they appear to have no effect, or again, I don't understand their role.

Anyway, there is this error message.

**Comment by kopiro** [comment]
Hey, please update to https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.4.5 where I added more debug logs and post your logs again.

**Comment by kopiro** [comment]
Update: you may be affected by [this issue](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551). Please follow [this guide](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/add_camera_with_new_firmware.md) on how to fix it.
