### ISSUE TITLE
Adding the unbridged accessory to Home

### ISSUE THREAD

**Issue by rbutler81** [kopiro/homebridge-tapo-camera#129]
**Describe Your Problem:**
The readme's last step says, "Once done you will have unbridged accessories, therefore you need to manually add them in your Home app."
There's no instruction on how to do this.. I've added a C200 to HomeBridge via this plugin, I can see the accessories on the HomeBridge "Accessories" page - they appear to be connected and working.
I can't get anything to show up in the Home app - what're the next steps?

I don't think I need to include logs, screenshots, etc.. I'm just looking for information on what to do next.

**Comment by Pascalx77** [comment]
Same problem over here, camera is working fine in Homebridge accessories page and in plugin camera UI visualization but do not appear in Home and I do not know what to do next at step ``Once done you will have unbridged accessories, therefore you need to manually add them in your Home app.``

**Comment by TEBandCo** [comment]
Add your bridge like usual, then go to iOS Home App > "+" Symbol (top right) > add Accessory > tap "More options..." > select the camera you want > use the PIN within HOOBS. Device will now be added.
