### ISSUE TITLE
Cameras not responding after power outage

### ISSUE THREAD

**Issue by Tbml-ctrl** [kopiro/homebridge-tapo-camera#138]
After power outage, cameras are not responding in HomeKit via home bridge tapo plugin. They do work in Tapo native app though. 

Cameras are with fixed IP. 
Mesh network with Fritz router and repeatiter. 

I have to restart secondary service plugin in order to work again in HomeKit. 

Does anyone have similar issue ?

**Comment by eiryu** [comment]
I was also restarting the homebridge itself when I was in that situation.

**Comment by Tbml-ctrl** [comment]
While waiting fix, I have found a alternative solution that restart Tapo child bridge via a plugin Cmdtriggerswitch2 and the command :

kill -15 $(pidof 'homebridge: homebridge-tapo-camera')

**Comment by kopiro** [comment]
This may be a corner case when StokRefresh gets into some sort of racing conditions. I did have tested this by switching off manually and it worked, though.

Can you maybe try with latest firmware?

Feel free to open this issue again.
