### ISSUE TITLE
v2.4.0 Some toggle states are reversed and alarm toggle does not disable

### ISSUE THREAD

**Issue by psycoticninja** [kopiro/homebridge-tapo-camera#150]
**Describe The Bug:**

I have updated the plugin to v2.4.0 and notice the following: 

Some of the toggle states are actually reversed, eg. Home/Homebridge says Privacy Mode toggle is 'On' but it is 'Off'.
 
When disabling the Alarm toggle - it does not actually get disabled on restart.

**To Reproduce:**

Review the accessory toggle states.

**Expected behavior:**

Privacy mode is disabled in Tapo app = Toggle state OFF etc.
Alarm toggle disabled in plugin = Do not show in Home app (screenshot from Homebridge but same issue occurs in Home app).

**Logs:**

Nothing to show here.

**Plugin Config:**

Shown in screenshots.

**Screenshots:**

<img width="521" alt="image" src="https://github.com/user-attachments/assets/d4afb8ec-0138-49df-9ecc-ba98c6569745">
<img width="556" alt="image" src="https://github.com/user-attachments/assets/f9cba509-bf71-44a2-bc73-65c41992e0eb">

**Environment:**

* **Plugin Version**: 2.4.0
* **Homebridge Version**:  1.8.4
* **Node.js Version**:  20.16.0
* **NPM Version**:  10.8.1
* **Operating System**:  Raspbian OS Lite

**Comment by kopiro** [comment]
Hello!

Regarding "Some of the toggle states are actually reversed, eg. Home/Homebridge says Privacy Mode toggle is 'On' but it is 'Off'", it's only for Privacy. Privacy is called "Eyes" so that the toggle is reversed - this way you can turn your camera via Siri and enable all the switches.

The alarm toggle was in fact not working for a typo, fixing soon.

**Comment by psycoticninja** [comment]
Sorry - I realised I had changed the name of “Eyes” but that makes sense now. Thanks for fixing up the Alarm as well and being so quick!

**Comment by avadiax** [comment]
Hi @kopiro the bug is still not fixed. You fixed the alarm but not the LED.

In your config.schema.json you use "disableLEDToggleAccessory", and in cameraAccessory.ts you stilluse "disableLedToggleAccessory". The "LED" spelling are different.
