### ISSUE TITLE
v2.4.x LED toggle bug

### ISSUE THREAD

**Issue by avadiax** [kopiro/homebridge-tapo-camera#154]
Hi @kopiro, with regards to issue #150 the LED toggle still has a bug. In your config.schema.json you use "disableLEDToggleAccessory", but in the cameraAccessory.ts you still use "disableLedToggleAccessory". Once the spelling inconsistency has been resolved (change from LED to Led) the toggle works.

_Originally posted by @avadiax in https://github.com/kopiro/homebridge-tapo-camera/issues/150#issuecomment-2267229241_

**Comment by kopiro** [comment]
Oh god - can't even spell properly. Thanks!
