### ISSUE TITLE
Is there a way to config camera that doesn't have RTSP?

### ISSUE THREAD

**Issue by minhkhoiii1997** [kopiro/homebridge-tapo-camera#159]
Hello, I just bought TC85 cameras, and looks like they don't have RTSP option anymore. Apparently there used to be an option under Advance Settings -> Camera Account to set up RTSP account, but for the latest firmware, looks like Tapo removed it for all battery cameras. I'm just wondering if there is a way for me to add camera without RSTP account?

**Comment by kopiro** [comment]
Unfortunately live view is only available via RTSP, sorry.
