### ISSUE TITLE
Failed to get snapshot or stream

### ISSUE THREAD

**Issue by Kelvas09** [kopiro/homebridge-tapo-camera#19]
Hi ! I don't see any issue template so I try like this.

First of all, thank you for your plugin !
I install Homebridge and your plugin to manage my C200 TP-Link camera. 

I successfully connected my camera to homebridge :
`[28/11/2021, 11:58:32] Tapo Cam Entrance A4C5 is running on port 39333.
[28/11/2021, 11:58:32] Please add [Tapo Cam Entrance A4C5] manually in Home app. Setup Code: 455-46-980
[28/11/2021, 11:58:32] Tapo Cam Living Room 0CE5 is running on port 43003.
[28/11/2021, 11:58:32] Please add [Tapo Cam Living Room 0CE5] manually in Home app. Setup Code: 455-46-980`

But when I add to HomeKit, I cannot preview video and cannot stream video (on the same network).

I have this error : 
`[Tapo Cam Entrance] Failed to fetch snapshot.`

And this one :
`[28/11/2021, 13:15:09] [TAPO-CAMERA] [Tapo Cam Living Room] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[28/11/2021, 13:15:09] [TAPO-CAMERA] [Tapo Cam Living Room] FFmpeg exited with code: 1 and signal: null (Error)
[28/11/2021, 13:15:09] [TAPO-CAMERA] [Tapo Cam Living Room] Stopped video stream.`

Do you have any idea?

Best regards

**Comment by Kelvas09** [comment]
I forget to tell you that I have ffmpeg installed with version 4.3.1.
And this is my config :

`{
            "platform": "TAPO-CAMERA",
            "cameras": [
                {
                    "name": "Tapo Cam Entrance",
                    "ipAddress": "192.168.1.12",
                    "password": "********",
                    "streamPassword": "*****",
                    "streamUser": "homebridge",
                    "pullInterval": 60000,
                    "debug": false,
                    "disableStreaming": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false,
                    "lowQuality": false
                },
                {
                    "name": "Tapo Cam Living Room",
                    "ipAddress": "192.168.1.16",
                    "password": "*****",
                    "streamPassword": "****",
                    "streamUser": "homebridge",
                    "pullInterval": 60000,
                    "debug": false,
                    "disableStreaming": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false,
                    "lowQuality": false
                }
            ]
        }`

**Comment by maerlin** [comment]
Hello! I was having the same problem. I've fixed it by doing:
- Change to a less complex password (mine had a few symbols)
- Rebooting the camera(s)
Voila', stream working. :)

**Comment by Kelvas09** [comment]
@maerlin Thanks for your reply! It's help me a lot and it's works!

it seems to me somewhat dangerous : the password is supposed to be hashed and thus not to have a symbol (well if they use a standard hash algorithm). So I'm afraid it's not, I hope I'm wrong ...

But thanks again for your help!

**Comment by kopiro** [comment]
hello! both the `streamPassword` and `password` in the config file must be clear-text, as the plugin will hash it accordingly before sending it.
