### ISSUE TITLE
Parameter settings for ffmeg?

### ISSUE THREAD

**Issue by BerlinSnoop** [kopiro/homebridge-tapo-camera#23]
Hi, 
at first, many thanks for your implementation of this plugin.

I have got a lot og error messages from the ffmpeg when I start a video stream. With the previous plugin I have used only the copy mode because the cam sends already H264 data. Is it possible to add this as an optional parameter? (And maybe parameters to the path of mmpeg? and additional parameters for ffmpeg itself?) I am using a Diskstation DS418 with arm64. 

Or do you have another idea for a solution?

Many thanks
Andreas

    `[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] Video stream requested: 1280 x 720, 30 fps, 299 `kbps`
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] Stream command: ffmpeg -i rtsp://doorcam:_12Kill34_@192.168.69.51:554/stream1 -an -sn -dn -codec:v copy -pix_fmt yuv420p -color_range mpeg -f rawvideo -payload_type 99 -ssrc 10669768 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params e4SDc4pzIcDvGSo4R3ZXJT48Xo7WtOyRpsLx8SUt srtp://192.168.69.33:60631?rtcpport=60631&pkt_size=1316 -vn -sn -dn -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 4771419 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params CpZi7Yb116pNonDgR/fCsQpb9cFvDuVGYGdFwCZY srtp://192.168.69.33:49814?rtcpport=49814&pkt_size=188 -loglevel level+verbose -progress pipe:1
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info] ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   built with gcc 8.4.0 (OpenWrt GCC 8.4.0 r1803-87cc54aa)
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   configuration: --enable-cross-compile --cross-prefix=aarch64-openwrt-linux-gnu- --arch=aarch64 --cpu=cortex-a53 --target-os=linux --prefix=/opt --pkg-config=pkg-config --enable-shared --enable-static --enable-pthreads --enable-zlib --disable-doc --disable-debug --disable-lzma --disable-vaapi --disable-vdpau --disable-outdevs --disable-runtime-cpudetect --enable-lto --enable-neon --enable-vfp --disable-x86asm --enable-gnutls --enable-libopus --enable-small --enable-libmp3lame --enable-gpl --enable-libx264
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libavutil      56. 51.100 / 56. 51.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libavcodec     58. 91.100 / 58. 91.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libavformat    58. 45.100 / 58. 45.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libavdevice    58. 10.100 / 58. 10.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libavfilter     7. 85.100 /  7. 85.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libswscale      5.  7.100 /  5.  7.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libswresample   3.  7.100 /  3.  7.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   libpostproc    55.  7.100 / 55.  7.100
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [tcp @ 0x1d98f780] [verbose] Starting connection attempt to 192.168.69.51 port 554
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [tcp @ 0x1d98f780] [verbose] Successfully connected to 192.168.69.51 port 554
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [verbose] SDP:
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] v=0
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] o=- 47078688 1 IN IP4 192.168.69.51
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] s=Session streamed by "TP-LINK RTSP Server"
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] i=stream1
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] t=0 0
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=tool:TP-LINK Streaming Media v2015.05.12
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=type:broadcast
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=control:*
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=range:npt=0-
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=x-qt-text-nam:Session streamed by "TP-LINK RTSP Server"
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] m=video 0 RTP/AVP 96
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] c=IN IP4 0.0.0.0
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] b=AS:8192
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=rtpmap:96 H264/90000
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=fmtp:96 packetization-mode=1; profile-level-id=640029; sprop-parameter-sets=Z2QAKawa0A8ARPyzcBAQFAAAAwAEAAADAAo8UIqA,aO4CckiQ
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=control:track1
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] m=audio 0 RTP/AVP 8
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] c=IN IP4 0.0.0.0
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] b=AS:64
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=rtpmap:8 PCMA/8000
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] a=control:track2
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] 
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [verbose] setting jitter buffer size to 500
[Wed Dec 29 2021 13:28:18 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [verbose] setting jitter buffer size to 500
[Wed Dec 29 2021 13:28:20 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [h264 @ 0x1d9909e0] [verbose] Reinit context to 1920x1088, pix_fmt: yuvj420p
[Wed Dec 29 2021 13:28:21 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [warning] max delay reached. need to consume packet
[Wed Dec 29 2021 13:28:21 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [warning] RTP: missed 4 packets
[Wed Dec 29 2021 13:28:21 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [h264 @ 0x1d9909e0] [error] error while decoding MB 83 49, bytestream -5
[Wed Dec 29 2021 13:28:21 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [h264 @ 0x1d9909e0] [info] concealing 2246 DC, 2246 AC, 2246 MV errors in P frame
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [warning] max delay reached. need to consume packet
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [warning] RTP: missed 1 packets
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [h264 @ 0x1d9909e0] [error] error while decoding MB 66 66, bytestream -5
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [h264 @ 0x1d9909e0] [info] concealing 223 DC, 223 AC, 223 MV errors in P frame
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [verbose] max_analyze_duration 5000000 reached at 5024000 microseconds st:1
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [rtsp @ 0x1d98d7e0] [info] decoding for stream 0 failed
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [warning] Guessed Channel Layout for Input Stream #0.1 : mono
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info] Input #0, rtsp, from 'rtsp://doorcam:_12Kill34_@192.168.69.51:554/stream1':
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   Metadata:
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]     title           : Session streamed by "TP-LINK RTSP Server"
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]     comment         : stream1
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]   Duration: N/A, start: 0.000000, bitrate: N/A
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]     Stream #0:0: Video: h264, 1 reference frame, yuvj420p(pc, bt709, progressive, left), 1920x1080 (1920x1088), 1 fps, 1 tbr, 90k tbn, 2 tbc
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [info]     Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [fatal] Unknown encoder 'libfdk_aac'
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] [AVIOContext @ 0x1d98f670] [verbose] Statistics: 0 seeks, 0 writeouts
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] FFmpeg exited with code: 1 and signal: null (Error)
[Wed Dec 29 2021 13:28:23 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] Stopped video stream.
[Wed Dec 29 2021 13:28:57 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] Snapshot requested: 1280 x 720
[Wed Dec 29 2021 13:28:57 GMT+0100 (CET)] [TAPO-CAMERA] [DoorCamMS] Snapshot command: ffmpeg -i rtsp://doorcam:_12Kill34_@192.168.69.51:554/stream1 -frames:v 1 -f image2 - -hide_banner -loglevel error
(node:12562) UnhandledPromiseReject `

**Comment by kopiro** [comment]
Let me check your requirements and I'll get back to you.

**Comment by BerlinSnoop** [comment]
I have seen now that I was using a different version of ffmpeg compiles with different parameters. Maybe it helps to have an option to specify the path to ffmpeg.

```
admin@SnoopBoxNAS:~$ /volume1/Appstore/ffmpeg/bin/ffmpeg -version
ffmpeg version 4.3.3 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 7.5.0 (GCC)
configuration: --target-os=linux --cross-prefix=/home/spksrc/ffmpeg-update/spksrc/toolchain/syno-aarch64-7.0/work/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/home/spksrc/ffmpeg-update/spksrc/spk/ffmpeg/work-aarch64-7.0/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/home/spksrc/ffmpeg-update/spksrc/spk/ffmpeg/work-aarch64-7.0/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/home/spksrc/ffmpeg-update/spksrc/toolchain/syno-aarch64-7.0/work/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-version3 --enable-fontconfig --enable-avresample --disable-debug --disable-static --disable-doc --extra-cflags=-DSYNO_VIDEOSTATION --extra-cflags=-fno-if-conversion --extra-cflags=-O3 --extra-cflags=-Wno-deprecated-declarations --enable-libxml2 --enable-demuxer=dash --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libbluray --enable-libspeex --enable-libtheora --enable-libvorbis --enable-gnutls --enable-libopus --enable-libsoxr --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libx265 --enable-libvpx --enable-libshine --enable-libzmq --enable-libzvbi --enable-libfdk-aac --enable-nonfree --enable-libaom --enable-libsvtav1 --arch=arm64 --enable-neon --enable-thumb --disable-yasm --disable-asm
```

**Comment by BerlinSnoop** [comment]
Hi again,
will find time in the near future to look into this?

**Comment by BerlinSnoop** [comment]
Hi again,
would it be possible implement this in the near future? (parameter for ffmpeg path)

**Comment by kopiro** [comment]
Hello, see: https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.1.0

**Comment by BerlinSnoop** [comment]
Many thanks for the new release but I believe it will not help me... Please see see the old ffmpeg config:

"name": "Camera FFmpeg",
    **"videoProcessor": "/volume1/@appstore/ffmpeg/bin/ffmpeg",**
    "porthttp": 8080,
    "localhttp": false,
    "cameras": [
        {
            "name": "DoorCam",
            "manufacturer": "TP-Link",
            "model": "C100",
            "serialNumber": "11111111",
            "firmwareRevision": "1.0.1",
            "motion": true,
            "doorbell": true,
            "switches": false,
            "motionTimeout": 5,
            "motionDoorbell": true,
            "unbridge": true,
            "videoConfig": {
                "source": "-rtsp_transport http -re -i rtsp://doorcam:XXXXXXXXXXX@192.168.69.51:554/stream1",
                "stillImageSource": "-rtsp_transport tcp -re -i rtsp://doorcam:XXXXXXXXXXXXXX192.168.69.51:554/stream1",
                "maxStreams": 4,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 30,
                "forceMax": false,
                "vcodec": "copy",
                "packetSize": 1316,
                "audio": true,
                "debug": false
            }
        }
    ],
    "_bridge": {
        "username": "0E:3E:73:1A:52:F8",
        "port": 41387
    },
    "platform": "Camera-ffmpeg"

**Comment by kopiro** [comment]
Can't you symlink that? 

`ln -s /volume1/@appstore/ffmpeg/bin/ffmpeg /usr/bin/ffmpeg`

**Comment by BerlinSnoop** [comment]
Yes, this is one option but not my favorite. It is not very stable against Synology updates. But I have tried this. At first with no result because it was using /opt/bin/ffmpeg (this version was too old too). Now I have change the symlink to this and video is working again 👍 . 
Another thing , the videoconfig is overwritten if the web UI is used.
Last thing, do you have tried to find out how the TAPO gets the still image? Grabbing it from the video stream is not the fastest way I think
