### ISSUE TITLE
Record motions / clips

### ISSUE THREAD

**Issue by Rahulsharma0810** [kopiro/homebridge-tapo-camera#31]
hi @kopiro 

First of all thanks for the wonderful work and making community life easy with your efforts.

I want to record clips or even continuous recording solution, do you have any idea or something I am missing, i even checked in ffmpeg plugin but no working example for recording.

**Comment by kopiro** [comment]
Hello; currently this plugin nor the official https://www.npmjs.com/package/homebridge-camera-ffmpeg package which this plugin is based on support this, sorry
