### ISSUE TITLE
Initialisation error in Hoobs

### ISSUE THREAD

**Issue by shamasis** [kopiro/homebridge-tapo-camera#32]
https://github.com/kopiro/homebridge-tapo-camera/blob/a6b9f3802c94462076b4bed79a46918d7b4edb67/src/cameraPlatform.ts#L33

Within Hoobs, this line errors out. Perhaps a check to continue in absence of `cameras` property would be helpful.

**Comment by kopiro** [comment]
Thank you, I'll fix this!
