### ISSUE TITLE
Is there a way to verify motion detection in logs?

### ISSUE THREAD

**Issue by LoutishDuke** [kopiro/homebridge-tapo-camera#46]
**Describe Your Problem:**
Is there a way to determine if motion is being detected properly in the logs? I don't get any notifications etc and can't see the tile alternating and my automation (which turns private mode on when motion is detected) doesn't activate, I'm new to this so not sure if everything is correct in the config below; I am getting the live feed with no error messages in the active homebridge log so I'm unsure what to do. I'm working with a C100 specifically, I am hoping to get it to trigger notifications when motion is detected through the home app. I appreciate that this might be a redundant question and do apologise if it has been asked before.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "tapo-camera",
            "videoProcessor": "/usr/bin/ffmpeg",
            "cameras": [
                {
                    "name": "TapoCamera_1",
                    "ipAddress": "192.168.0.47",
                    "password": "pass1",
                    "streamPassword": "pass2",
                    "streamUser": "user",
                    "pullInterval": 60000,
                    "disableStreaming": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false,
                    "lowQuality": false,
                    "motion": true,
                    "videoConfig": {
                        "source": "-i rtsp://user:pass2@192.168.0.47:554/stream1",
                        "stillImageSource": "-re -i rtsp://user:pass2@192.168.0.47:554/stream1",
                        "maxWidth": 1024,
                        "maxHeight": 576,
                        "maxFPS": 10,
                        "audio": true,
                        "debug": true
                    }
                }
            ]
        }
    ]
```

**Screenshots:**

**Environment:**

* **Plugin Version**:  2.2.0
* **Homebridge Version**: 1.3.9
* **Node.js Version**: 16.13.2
* **NPM Version**: 8.3.1
* **Operating System**: Raspbian

**Comment by kopiro** [comment]
Hey, please remove the `videoConfig` key and try again; you don't need to override that if you're not completely sure of what you're doing.

**Comment by LoutishDuke** [comment]
Hi, thanks, I've removed the key and subfields;  there is still no notification of motion detected.

**Comment by kopiro** [comment]
Have you solved? :)
