### ISSUE TITLE
Motion sensor not working

### ISSUE THREAD

**Issue by maxime-killinger** [kopiro/homebridge-tapo-camera#50]
**Describe The Bug:**
The motion sensor is not working since the last update

**To Reproduce:**
Update the plugin to 2.2.1, try the motion sensor

**Expected behavior:**
Motion sensor triggered on motion

**Plugin Config:**

```json
        {
            "cameras": [
                {
                    "name": "Salon",
                    "ipAddress": "**",
                    "password": "**",
                    "streamUser": "**",
                    "streamPassword": "**",
                    "debug": false,
                    "lowQuality": true
                }
            ],
            "platform": "tapo-camera"
```

**Environment:**

* **Plugin Version**: 2.2.1
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.14.0
* **NPM Version**: 8.3.1
* **Operating System**: Docker

**Comment by kopiro** [comment]
Hello; thanks for reporting, just tested this on a fresh homebridge instance and no problem here.
