### ISSUE TITLE
The homekit application does not see the camera - it did before

### ISSUE THREAD

**Issue by mazdamer** [kopiro/homebridge-tapo-camera#51]
I added the camera according to the instructions, the bridge for the camera was added in the HK application. Unfortunately, when I want to add a camera, HK does not see it. Previously, it worked without a problem. What could be the reason? IOS 15.4?

 {
            "cameras": [
                {
                    "name": "MGCam",
                    "ipAddress": "xx.xx.xx.3",
                    "password": "xxxxxxxxxxxxxx",
                    "streamUser": "xxxxxxxxxx",
                    "streamPassword": "xxxxxxxxxxxxxx",
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false
                }
            ],
            "_bridge": {
                "username": "xx:xx:xx:76:A3:55",
                "port": 35940
            },
            "platform": "tapo-camera"
        }
    ],
    "accessories": []
}

**Comment by macecchi** [comment]
I'm having the same issue. I had it working before and then removed the accessory after playing around with other plugins. And now I can't get it to show up to add accessory again :(

**Comment by cmeliak** [comment]
I'm sure the camera doesn't show in homekit  :/

**Comment by kopiro** [comment]
Hey, installed on a fresh Homebridge instance here; no problem in adding the camera.
Try to check if some other plugin is interfering.
