### ISSUE TITLE
Hello, can you add the possibility to take a screen from a camera and save it in gallery? In this way you can create an automation that every 1 hour, you receive a notification with that screen.

### ISSUE THREAD

**Issue by ALF-2021** [kopiro/homebridge-tapo-camera#62]
Am I enough clear?

Thanks. 

Best regards. 

**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kopiro** [comment]
Hello; I don't think that this is possible with HomeKit.
