### ISSUE TITLE
What's the HomeKit code to add the camera to HomeKit

### ISSUE THREAD

**Issue by Laro1979** [kopiro/homebridge-tapo-camera#63]
My Pi crashed and I installed all plug-ins from scratch and I used this earlier and it worked like a charm. But nom I can't for the love off good add my camera to the HomeKit because I can't find the HomeKit code to enter manually.

I can se and control the camera in Homebridge, but I can not get it in to the Home app. I tried several times to delete tha plugin and install it again. I try to use the HomeKit code of my Homebridge but the camera is never found. I deleted the entire homebridge in the Home app and reconnected it. everything else pops up and work, but not the Tapo camera even if I can se it and control it in Homebridge... I am getting crasy

**Comment by kopiro** [comment]
Your Homekit code is in the homebridge dashboard, either as log or as QR code

**Comment by Laro1979** [comment]
Thanks for replying. 

I have used the HomeKit code and the QR code from the Homebridge. But the camera never shows in HomeKit. 

I have deleted the bridge in HomeKit and connected it again. Several times. Everything else than my Tapo camera shows up in the HomeKit app. 

I have installed and uninstalled the plugin several times. 

Nothing helps. 

I can control the camera through the Homebridge accessory and I can se in the Tapo app that it works, for example if I turn on and off the privacy mode. So it seems like everything in Homebridge is working fine. There is no errors in the log. 

The camera just won’t show up in HomeKit

It has been working fine for over a year. But then my pi crashed and I had to reinstall everything. And this is the only thing I can’t get to work again. 

By the way. Are you interested in making this for plug in for the Athom Homey Pro bridge?

Best regards 
Lars

Den 24. sep. 2022 kl. 13.07 skrev Flavio De Stefano <notifications@github.com>:

﻿
Your Homekit code is in the homebridge dashboard, either as log or as QR code

**Comment by Laro1979** [comment]
Thanks for replying. I have used the HomeKit code and the QR code from the Homebridge. But the camera never shows in HomeKit. I have deleted the bridge in HomeKit and connected it again. Several times. Everything else than my Tapo camera shows up in the HomeKit app. I can control the camera through the Homebridge accessory and I can se in the Tapo app that it works, for example if I turn on and off the privacy mode. So it seems like everything in Homebridge is working fine. There is no errors in the log. The camera just won’t show up in HomeKitIt has been working fine for over a year. But then my pi crashed and I had to reinstall everything. And this is the only thing I can’t get to work again. By the way. Are you interested in making this for plug in for the Athom Homey Pro bridge?Best regards LarsDen 24. sep. 2022 kl. 13.07 skrev Flavio De Stefano ***@***.***>:﻿
Your Homekit code is in the homebridge dashboard, either as log or as QR code

**Comment by Metatropics** [comment]
> Your Homekit code is in the homebridge dashboard, either as log or as QR code.
> 
> You need to manually add the camera in HomeKit by clicking "Add accessory"

I'm getting incorrect code.

**Comment by nisus91** [comment]
I am in the same situation as above. 
Let me know when you know a solution.

> > Your Homekit code is in the homebridge dashboard, either as log or as QR code.
> > You need to manually add the camera in HomeKit by clicking "Add accessory"
> 
> I can add bridge with QR code. But when trying to add camera the home bridge code or bridge QR do not work.

**Comment by Laro1979** [comment]
Have any of you succeded in getting the camera to show up on Homekit again?

I have deleted everything and installed everything again. I can´t for the love of christ not get this app to work, the camera does not show up in Homekit, but I can control the camera through this app. for exampel if I open the original Tapo camera app on my phone so I can se the videostream, then if I enable privacy mode in this homebridge app, then the camera goes to privacemode in the original Tapo app.
So I know it is connected correctly, but the videofeed / camera does not show up in the apple Home app..

**Comment by Metatropics** [comment]
FWIW: I moved my TAPO's from Homebridge to Scrypted with the ONVIF plugin. Besides no privacy mode, everything perfect.

**Comment by BSCTech70** [comment]
I have the same issue--no camera feed will show up in HomeKit after adding the HUB and following the instructions.

**Comment by Laro1979** [comment]
> I have the same issue--no camera feed will show up in HomeKit after adding the HUB and following the instructions.

I solved this by removing the HUB and start over, then when I added things again I added the camera first with the homnekitcode, and afterwards the HUB itself. Now everything works fine.

**Comment by Laro1979** [comment]
> I am in the same situation as above. Let me know when you know a solution.
> 
> > > Your Homekit code is in the homebridge dashboard, either as log or as QR code.
> > > You need to manually add the camera in HomeKit by clicking "Add accessory"
> > 
> > 
> > I can add bridge with QR code. But when trying to add camera the home bridge code or bridge QR do not work.

I solved this by removing the HUB and start over, then when I added things again I added the camera first with the homnekitcode, and afterwards the HUB itself. Now everything works fine.

**Comment by BSCTech70** [comment]
That worked to get the Camera Feed to show up in HomeKit; however, it won't display live stream....get the following in the logs:
[3/7/2023, 1:38:11 PM] [homebridge-tapo-camera] [Office Surveil] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[3/7/2023, 1:38:12 PM] [homebridge-tapo-camera] [Office Surveil] FFmpeg exited with code: 1 and signal: null (Error)
[3/7/2023, 1:38:12 PM] [homebridge-tapo-camera] [Office Surveil] Stopped video stream.

**Comment by eiklin** [comment]
Hi all, try adding the camera using Add Accessory -> More Options -> {Tapo Camera Name}. When prompted for the setup code, use the PIN displayed under the main page of the Tapo Camera Bridge.
