### ISSUE TITLE
Error during setup of camera Backdoor Camera ONVIF SOAP Fault: Authority failure

### ISSUE THREAD

**Issue by netsmith** [kopiro/homebridge-tapo-camera#65]
I have two taps cameras which were working through home bridge and visible in the Home App. Network remains unchanged but now they no longer are visible. They still work fine with the TAPO app. I did reset the password on them, but I have copied that password across to the settings but it gives the following error message.

See above, were working but not now Only thing I've done recently is changed the password. Im not sure where the streaming password comes from (or how I find it) but I've assumed it was the same as the taps app password?

[12/10/2022, 17:13:32] [homebridge-tapo-camera] Error during setup of camera Backdoor Camera ONVIF SOAP Fault: Authority failure
[12/10/2022, 17:13:32] [homebridge-tapo-camera] Error during setup of camera Kitchen ONVIF SOAP Fault: Authority failure

```
```

**Plugin Config:**

```json
This is the part of the config file

            "cameras": [
                {
                    "name": "Backdoor Camera",
                    "ipAddress": "192.168.0.57",
                    "password": "password",
                    "streamUser": "xxxxx",
                    "streamPassword": "same as password"
                },
                {
                    "name": "Kitchen",
                    "ipAddress": "192.168.0.189",
                    "password": "password",
                    "streamUser": "xxx",
                    "streamPassword": "same as password"
                }
            ],
            "_bridge": {
                "username": "xxx",
                "port": 43150
            },
            "platform": "tapo-camera"
        },

```

**Screenshots:**

**Environment:**

* **Plugin Version**:
Homebridge version: v1.5.0
Node.js Version | v16.16.0
-- | --

Node.js Version	[v16.16.0](https://homebridge.io/w/JTKEF)
* **Operating System**:

**Comment by kopiro** [comment]
Hello; as in documentation, the credentials are the one you set in Settings > Advanced Settings > Camera Account.
