### ISSUE TITLE
CPU usage high on RPi

### ISSUE THREAD

**Issue by alexhull24** [kopiro/homebridge-tapo-camera#7]
Managed to test this with a Tapo C200, but noticed that the settings for video for the camera are causing the host device for homebridge (in my case a Raspberry Pi 3B+) to re-encode the video stream.

I also have this camera setup via Homebridge Camera FFMPEG and found that for best performance you can use the following settings to avoid this:

 "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Cam 1",
                    "manufacturer": "Tapo",
                    "model": "C200",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://_address_",
                        "vcodec": "copy",
                        "videoFilter": "none",
                        "audio": true
}
]

With homebridge-tapo-camera I see over 50% CPU usage when streaming the video, whereas with settings above on homebridge camera ffmpeg I see around 3%.

I'm really glad to see a dedicated plug-in for Tapo cameras, the addition of the switches is really very useful, although I had to set them in HomeKit to 'show as separate tiles' otherwise once turned off, they disappear... Can raise a separate issue for that if desired.

I am curious if the motion detection for Tapo can be utilised in HomeKit as notifications? Is there a reason why this is omitted?

**Comment by kopiro** [comment]
Hello; this is amazing!

I haven't actually checked the CPU on the board, but I'll test your settings and include them in the project; let you know in a bit :)

**Comment by kopiro** [comment]
Version 1.3.0 implements these changes: https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v1.3.0
Thanks again ;)
