### ISSUE TITLE
[homebridge-tapo-camera] Error during setup of camera undefined  The "data" argument must be ...

### ISSUE THREAD

**Issue by lngb** [kopiro/homebridge-tapo-camera#73]
Hello !
I'm trying to configure my Tapo camera with Homebrige, thru "Homebridge Tapo Camera" Plugin, 
but once i inserted all the data for connection to rtsp protocol of the Tapo Camera, the following error
is displayed in the Homebridge dashboard:

_[homebridge-tapo-camera] Error during setup of camera undefined  The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined_

It's not possibile to see the streaming neither in Homebridge App nor in HomeKit integration in Home App.

Someone could help me ? 
Thank you very much !

**Comment by kopiro** [comment]
Hello, can you paste your configuration?

**Comment by joseansau** [comment]
I have had the same problem, after a while of tests I have managed to solve it in the following way:

1.- Uninstall the plugin.
2.- Enter Homebridge settings:
      - Remove All Accessories from Cache
      - Unpair Bridges / Cameras / TVs / External Accessories
      - Restart Homebridge Accessory
      
3.- Reinstall the plugin (only install, do not configure yet).
4.- Update device (in my case Raspberry "apt-get update" and "apt-get upgrade"), in case there is an update of something.
5.- Restart the device.
6.- Configure plugin and cross your fingers.


Sorry for my English, I had to use the translator.

**Comment by los1987** [comment]
Hi, I am also having the same problem.  

here is my config.  It is a TC70 camera. 


[tapo-camera] Initializing tapo-camera platform...
[24/07/2023, 20:50:46] [tapo-camera] Error during setup of camera undefined The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

Hope someone can help!

    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "xx
                "cookies": "xx
            },
            "platform": "Nest"
        },
        {
            "cameras": [
                {
                    "ipAddress": "192.168.0.xx",
                    "password": "xx",
                    "streamUser": "xx",
                    "streamPassword": "xx"
                }
            ],
            "platform": "tapo-camera"
        }
