### ISSUE TITLE
Possibility to move the camera

### ISSUE THREAD

**Issue by MikeDevresse** [kopiro/homebridge-tapo-camera#74]
Hi,
First I want to say great job, this works exactly as intended!
I would like to know if there is a possibility to move the camera? In the Tapo app there is the pan & tilt functionality but I haven't found a way to do this from the Home app.
Thank you!

**Comment by kopiro** [comment]
Hello; unfortunately this feature is not supported yet, but I intend to make it work in the future.
Thanks!
