### ISSUE TITLE
Error when starting the plugin - Camera does not show in Home app but shows in HomeBridge dashoard

### ISSUE THREAD

**Issue by tatdathoang** [kopiro/homebridge-tapo-camera#78]
**Describe The Bug:**
The camera does not appear in Home app on iOS after adding the bridge.
The video feed however does show in the home bridge dashboard.
Home bridge log shows error included below

**To Reproduce:**
Install the plugin on Home bridge.

**Expected behavior:**
The camera is availabble in the Home app on iOS devices.

**Logs:**
Error at 'getStatusAndUpdateCharacteristics'. FetchError: request to https://192.168.xxx.xxx/ failed, reason: socket hang up
    at ClientRequest.<anonymous> (/var/lib/hoobs/tapocamerabridge/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketOnEnd (node:_http_client:518:9)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

**Plugin Config:**

{
    "platform": "tapo-camera",
    "cameras": [
        {
            "name": "camera name",
            "ipAddress": "192.168.xxx.xxx",
            "password": " tp link password here",
            "streamUser": "on device account - normal characters only",
            "streamPassword": "on device account - normal characters only"
        }
    ]
}

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.2.3
* **Homebridge Version**: 4.3.0
* **Node.js Version**: none
* **NPM Version**: none
* **Operating System**: Home bridge HOOBS

**Comment by swittk** [comment]
I'm encountering this as well

**Comment by Maikysupra** [comment]
Same problem here. All set up and the bridge was added to the HOME app successfully but no accessory (video) available. 

Plugin Version: 2.2.3
HOOBS Version: 4.3.0
Homebridge Version: 1.6.0
Node Version: 16.20.1

**Comment by tatdathoang** [comment]
Solution: after adding the bridge and the camera to Home, open the menu of the Home app and select the camera that is now pending to be added. It will ask for the setup code which you find in the bridge setting

**Comment by Maikysupra** [comment]
> Solution: after adding the bridge and the camera to Home, open the menu of the Home app and select the camera that is now pending to be added. It will ask for the setup code which you find in the bridge setting

Thanks for your prompt response. Unfortunately I don’t have any pending accessory available in my home menu. I have also tried re-install / uninstall the plugin several times, incl. tweaks to the settings but no joy.

**Comment by ScjMitsui** [comment]
Open the Home app, select "Add Accessory", then "More options...". You will find the camera nearby and ready to be added.

**Comment by radityakurnianto** [comment]
> Open the Home app, select "Add Accessory", then "More options...". You will find the camera nearby and ready to be added.

for me, this only work once. the next i try to do it again, it doesn't working
