### ISSUE TITLE
"Privacy Mode", "Alarm" and a "motion detection" accessory didn't work anymore since the last TP-Link update

### ISSUE THREAD

**Issue by B3ckons** [kopiro/homebridge-tapo-camera#80]
**Describe The Bug:**

"Privacy Mode", "Alarm" and a "motion detection" accessory didn't work anymore 
since the last TP-Link update  at a TP-Link Tapo C200 to Version 1.3.4

- Apple Homes Report: "No Response"

**To Reproduce:**

Upgrade a Tapo C200 to newest Version 1.3.4

**Expected behavior:**

The three accessories works normal

**Logs:**
[tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. FetchError: request to https://192.168.X.X/ failed, reason: socket hang up
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-tapo-camera/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketOnEnd (node:_http_client:526:9)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

**Plugin Config:**

            "cameras": [
                {
                    "name": "Smart-Cam-01",
                    "ipAddress": "192.168.X.X",
                    "password": "XXXX,
                    "streamUser": "YYYYYY",
                    "streamPassword": "ZZZZZ",
                    "debug": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false
                },
                {
                    "name": "Smart-Cam-02",
                    "ipAddress": "192.168.X.X",
                    "password": "XXXXX",
                    "streamUser": "YYYYY",
                    "streamPassword": "ZZZZZZ"
                }
            ],
            "platform": "tapo-camera"

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.2.3
* **Homebridge Version**: V1.6.1
* **Node.js Version**:  v18.16.0
* **NPM Version**: v9.5.1
* **Operating System**: Raspbian

**Comment by salboa** [comment]
I have the exact same problem with TP-Link Tapo C200 Version 1.3.4.

My environment is:

- Plugin Version: 2.2.3
- Homebridge Version: V1.6.1
- Node.js Version: v18.16.0
- NPM Version: v9.5.1
- Operating System: Ubuntu server 22.04

 
The TP-Link Tapo C210 instead works well.

**Comment by shapetheLOLa** [comment]
same here

**Comment by thugleifi** [comment]
I have the same problem, anyone figured out a solution? Bought the c200 to use as a baby monitor and would love to be able to get the notifications and videostream pop up on my apple tv again!

**Comment by OnishaX** [comment]
Hi, I was having this issue too. The most recent firmware has fixed this issue for me.

I have it working now and here are the details about my camera:
version: 1.3.5
Build: 230717
Rel.47395n(4555)
Hardware version: 3.0
Plugin: homebridge-tapo-camera v2.2.3

**Comment by shapetheLOLa** [comment]
There is no 1.3.5 for me yet as of now :( but glad to hear it’s fixed in a new version!

**Comment by shapetheLOLa** [comment]
Just checked, Im on that firmware also now. Still the same issues for me

**Comment by thugleifi** [comment]
No firmware update available for me, also forgot to mention, I don't even get the video stream anymore either. It just stuck on loading until it says no response. Homebridge says  
"Starting video stream: native x native, native fps, ??? kbps (AAC-eld)" in homebridge

Tried removing and adding the camera again in the home app. What region are you in where the update is available?

**Comment by OnishaX** [comment]
I’m in New Zealand.. also I don’t have the tplink cloud subscription… if that’s important idk

**Comment by salboa** [comment]
Hi guys,
I confirm that after firmware upgrade from 1.3.4 to latest (1.3.5) the camera restarted  to work properly with homebridge.

**Comment by thugleifi** [comment]
> Hi guys, I confirm that after firmware upgrade from 1.3.4 to latest (1.3.5) the camera restarted to work properly with homebridge.

Is there any other way to update than through the app? 

Mine says I have the latest update while showing "Version 1.3.4 Build 230424 Rel76394n(4555)

Located in Sweden, if that makes any difference

**Comment by B3ckons** [comment]
Thank you very Match 👍.
I also Iconfirm that after firmware upgrade from 1.3.4 to latest 1.3.5,  the camera restarted to work properly with homebridge.
