### ISSUE TITLE
C510 - How to add in home?

### ISSUE THREAD

**Issue by Bitweidi** [kopiro/homebridge-tapo-camera#84]
Hi there!

Got a new C510 PTZ Camera. Installed the plugin in my homebridge, added the camera and i can see it in the homebridge dashboard.

Now if i want to add it to my Home App on iPhone, i can find the camera but then i have to put a configuration code. Can you tell me where to find this code? (Normally it should be delivered with official homekit devices).

Thank you!

**Comment by eliteladen** [comment]
Hi, did you manage to find the answer to this?

**Comment by amine250** [comment]
@Bitweidi @eliteladen I tried the homebridge code at the homepage and it worked
