### ISSUE TITLE
Support for C420/H200

### ISSUE THREAD

**Issue by gebjeff** [kopiro/homebridge-tapo-camera#86]
How do I configure the plugin for a C420 camera and its H200 Hub when I don't have a Tapo cloud account?

I've purchased and installed a Tapo C420 camera and its H200 Hub. I can see the camera in the Tapo app version 2.17.201. I don't have a Tapo cloud account, but do have a TP-Link account that I use in the Tapo app. While I have assigned a static ip address to the H200 hub, it appears that the camera does not have an IP address (validated through a nmap run). The H200 hub open ports are tcp 443 and 8800.

The current iphone version of the Tapo app does not have a "Settings > Advanced Settings > Camera Account"., so i can't find the __STREAM_USER__ and __STREAM_PASSWORD__.

How do I configure the plugin to support the C420/H200?

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: v2.2.3 
* **Node.js Version**: v18.17.1
* **NPM Version**: v18.17.1
* **Operating System**: Debian GNU/Linux 11 (bullseye)

**Comment by macsoftware** [comment]
I was wondering something similar for the Tapo D230 Doorbell Camera as well. I have a static IP address for the doorbell but there is no Camera Account.
Is this something that we need to get TPLink to get on to or is there a way to connect to it without?

**Comment by john-catalano** [comment]
Bump for interest. I have the same c420/h200 package. I was fairly certain that Tapo listed the C420 as having RTSP/ONVIF support, but it seems not to be the case. That, and the support people in the Tapo forums claim that such a setup is impossible with battery cameras.

**Comment by midnightcomesonce** [comment]
Still no workaround on this?

**Comment by macsoftware** [comment]
Was there a resolution to this or is it unlikely to be resolved so is just closed?

**Comment by whatamanoffical** [comment]
@macsoftware there is no resolution atm as TP-LINK needs to implement the RTSP/ONVIF on their side. You could raise awareness and upvote this matter in tp-community as a feature request.
