### ISSUE TITLE
ECONNRESET with Tapo C200

### ISSUE THREAD

**Issue by psycoticninja** [kopiro/homebridge-tapo-camera#93]
**Describe The Bug:**

I have two Tapo C200's:
One is running Version 1.3.9 Build 231019 Rel.38052n(4555) - HW 2.0
The other is running Version 1.3.9 Build 231019 Rel.37378n(4555) - HW 1.0

Since upgrading both to 1.3.9 XXXX the one with HW 2.0 no longer connects to Homebridge, reporting the following error in the logs:
```[22/11/2023, 08:14:42] [homebridge-tapo-camera] Error during setup of camera Rat Cam read ECONNRESET```

The camera appears to be working fine via RTSP - it is also streaming to Shinobi and have no issues there.

I have tried to remove the single camera accessory from Homebridge settings, renamed the camera in the plugin configuration as well but still same error.

**To Reproduce:**

Not sure how to reproduce this.

**Expected behavior:**

Camera should just work.

**Logs:**

```[22/11/2023, 08:14:42] [homebridge-tapo-camera] Error during setup of camera Rat Cam read ECONNRESET```

**Environment:**

* **Plugin Version**: 2.2.3
* **Homebridge Version**:  1.7.0
* **Node.js Version**:  18.18.2
* **NPM Version**:  9.8.1
* **Operating System**:  Debian GNU/Linux Bullseye (11)  - Raspbian Lite

**Comment by bbottin** [comment]
Latest update(s) keeps restarting HomeBridge, keep getting status not running, check logs error. I have now disabled the plugin and errors have stopped.

**Comment by aswathraja** [comment]
> Latest update(s) keeps restarting HomeBridge, keep getting status not running, check logs error. I have now disabled the plugin and errors have stopped.

Had the same issue, downgrading to 2.3.1 fixed the issue for me.

**Comment by aswathraja** [comment]
> > Latest update(s) keeps restarting HomeBridge, keep getting status not running, check logs error. I have now disabled the plugin and errors have stopped.
> 
> Had the same issue, downgrading to 2.3.1 fixed the issue for me.

Just quick debugging of the code. I understood that md5 hashed tapo password doesn't work. I believe its because the encryption_type passed the API call for login is hard coded to "3" - I must say I dont know what that corresponds to. 

Having the tapo password as sha256 hashed gives the error "Invalid Device Confirm". Will continue to debug it later. 

@kopiro Hope this helps and surely its some pesky little bug that you can fix easily and understand better.

**Comment by psycoticninja** [comment]
@kopiro this did not resolve my issue - which appears to be unrelated to what others reported in this thread.

This still exists:
```
[22/11/2023, 08:14:42] [homebridge-tapo-camera] Error during setup of camera Rat Cam read ECONNRESET
```

Any ideas? RTSP is working fine, Shinobi can stream this camera no issues. Something must have changed with Tapo API?
