### ISSUE TITLE
Failed to load plugins config schema

### ISSUE THREAD

**Issue by ppapajohn** [kopiro/homebridge-tapo-camera#96]
Hi all, 

Following the upgrade to version 2.3.0, the settings tab cannot load. The error I receive is the subject, while when i revert back to the previous version I can apply the desired configuration normally via the UI. The config file contains the necessary entries, I can edit them manually. 

In advance, thank you for your time and support!

Best Regards,
Panos

**Comment by Lubinko** [comment]
the same for me

**Comment by daciand** [comment]
I have exactly the same issue as well.

**Comment by kopiro** [comment]
Fixed in https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.3.1

**Comment by Lubinko** [comment]
thnx so much!
